# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimSaaS', '0002_auto_20170619_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='trackImage_Off',
            field=models.FileField(default='trackImages/AddPlot_hover.png', upload_to='trackImages/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='trackImage_On',
            field=models.FileField(default='trackImages/AddPlot_hover.png', upload_to='trackImages/'),
        ),
    ]
