# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimSaaS', '0003_auto_20170620_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='jobOverview',
            field=models.FileField(default='jobOverviews/jobOverview.json', upload_to='jobOverviews/'),
        ),
    ]
