# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SimSaaS', '0004_auto_20170619_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SimSaaS.League'),
        ),
    ]
