# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimSaaS', '0005_auto_20170620_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='jobOverviewFile',
            field=models.FileField(upload_to='jobOverviews/'),
        ),
    ]
